spring.application.name=backend

spring.datasource.url=jdbc:postgresql://ep-empty-glade-b4cs37rk-pooler.c-6.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET}